version: '2'

volumes:
  data:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: basic
    ports:
      - '3000:3000'
    depends_on:
      - mariadb
      - postgres
    container_name: go-web
    environment:
      - LAGOON_TEST_VAR=test
      - LAGOON_GIT_SHA=SHA256
      - LAGOON_ENV=Dev
      
  mariadb:
    image: uselagoon/mariadb-10.6
    labels:
      lagoon.type: mariadb
    ports:
      - '3306'

  postgres:
    image: uselagoon/postgres-14
    labels:
      lagoon.type: postgres
    ports:
      - '5432'

  solr:
    image: uselagoon/solr-8
    labels:
      lagoon.type: solr
    ports:
     - "8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - mycore

  redis:
    image: uselagoon/redis-6
    labels:
      lagoon.type: redis
    ports:
      - '6379'
