version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    container_name: go-web
    environment:
      - 'DB_PORT=3305'
      - 'DB_HOST=database'
      
  mariadb:
    image: mariadb:10.4
    ports:
      - 3305:3305
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MARIADB_PASSWORD=api
      - MARIADB_USER=api
      - MARIADB_DATABASE=infrastructure