version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: basic
    ports:
      - '3000:3000'
    depends_on:
      - mariadb
      - postgres
    container_name: go-web
    environment:
      - LAGOON_TEST_VAR=test
      
  mariadb:
    image: uselagoon/mariadb-10.6
    labels:
      lagoon.type: mariadb
    ports:
      - '3306'
    # environment:
    #   - MARIADB_PASSWORD=lagoon
    #   - MARIADB_USERNAME=lagoon
    #   - MARIADB_DATABASE=lagoon
    #   - MARIADB_ROOT_PASSWORD=Lag00n

  postgres:
    image: uselagoon/postgres-14
    labels:
      lagoon.type: postgres
    ports:
      - '5432'
    # environment:
    #   - POSTGRES_USERNAME=lagoon
    #   - POSTGRES_PASSWORD=lagoon
    #   - POSTGRES_DB=lagoon